AtlasTracker/Models/Ticket.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AtlasTracker.Models;

public class Ticket
{
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    [DisplayName("Ticket Title")]
    public string? Title { get; set; }

    [Required]
    [StringLength(2000)]
    [DisplayName("Ticket Description")]
    public string? Description { get; set; }

    [DataType(DataType.Date)]
    [DisplayName("Created")]
    public DateTimeOffset Created { get; set; }

    [DataType(DataType.Date)]
    [DisplayName("Updated")]
    public DateTimeOffset? Updated { get; set; }

    [DisplayName("Archived")]
    public bool Archived { get; set; }

    [DisplayName("Archived by Project")]
    public bool ArchivedByProject { get; set; }

    public int ProjectId { get; set; }

    public int TicketTypeId { get; set; }

    public int TicketPriorityId { get; set; }

    public int TicketStatusId { get; set; }

    [Required]
    public string? OwnerUserId { get; set; }

    public string? DeveloperUserId { get; set; } 
    
   
    // Navigation Properties
    [DisplayName("Project")]
    public virtual Project? Project { get; set; }
    public virtual TicketPriority? TicketPriority { get; set; }
    public virtual TicketType? TicketType { get; set; }
    public virtual TicketStatus? TicketStatus { get; set; }
    public virtual BTUser? OwnerUser { get; set; }
    public virtual BTUser? DeveloperUser { get; set; }

    public virtual ICollection<TicketComment> Comments { get; set; } = new HashSet<TicketComment>();
    public virtual ICollection<TicketAttachment> Attachments { get; set; } = new HashSet<TicketAttachment>();
    public virtual ICollection<TicketHistory> History { get; set; } = new HashSet<TicketHistory>();
    public virtual ICollection<Notification> Notification { get; set; } = new HashSet<Notification>();
    
    
}

AtlasTracker/Models/TicketType.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AtlasTracker.Models;

public class TicketType
{
    
    public int Id { get; set; }

    [Required] [DisplayName("Type Name")] public string? Name { get; set; }
}

AtlasTracker/Models/ViewModels/AssignDeveloperViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AtlasTracker.Models.ViewModels;

public class AssignDeveloperViewModel
{
    public Project? Project { get; set; }
    public SelectList? PMList { get; set; }
    public string? PMID { get; set; }
}

AtlasTracker/Controllers/TicketsController.cs
// #nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AtlasTracker.Data;
using AtlasTracker.Extensions;
using AtlasTracker.Models;
using AtlasTracker.Models.Enums;
using AtlasTracker.Models.ViewModels;
using AtlasTracker.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace AtlasTracker.Controllers
{
    public class TicketsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<BTUser> _userManager;
        private readonly IBTProjectService _projectService;
        private readonly IBTLookupService _lookupService;
        private readonly IBTCompanyInfoService _companyInfoService;
        private readonly IBTFileService _fileService;
        private readonly IBTTicketService _ticketService;
        private readonly IBTTicketHistoryService _ticketHistoryService;

        public TicketsController(ApplicationDbContext context,
            UserManager<BTUser> userManager,
            IBTLookupService lookupService,
            IBTProjectService projectService,
            IBTFileService fileService,
            IBTCompanyInfoService companyInfoService,
            IBTTicketService ticketService,
            IBTTicketHistoryService ticketHistoryService)
        {
            _context = context;
            _userManager = userManager;
            _lookupService = lookupService;
            _projectService = projectService;
            _fileService = fileService;
            _companyInfoService = companyInfoService;
            _ticketService = ticketService;
            _ticketHistoryService = ticketHistoryService;
        }

        // GET: Tickets
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Tickets
                .Include(t => t.DeveloperUser)
                .Include(t => t.OwnerUser)
                .Include(t => t.Project)
                .Include(t => t.TicketPriority)
                .Include(t => t.TicketStatus)
                .Include(t => t.TicketType);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: My Tickets
        public async Task<IActionResult> MyTickets()
        {
            // string userId = _userManager.GetUserId(User);
            // int companyId = User.Identity.GetCompanyId();
            BTUser btUser = await _userManager.GetUserAsync(User);

            List<Ticket> tickets = await _ticketService.GetTicketsByUserIdAsync(btUser.Id, btUser.CompanyId);

            return View(tickets);
        }

        // GET: All Tickets
        public async Task<IActionResult> AllTickets()
        {
            int companyId = User.Identity.GetCompanyId();

            List<Ticket> tickets = await _ticketService.GetAllTicketsByCompanyAsync(companyId);

            if (User.IsInRole(nameof(BTRole.Developer)) || User.IsInRole(nameof(BTRole.Submitter)))
            {
                return View(tickets.Where(t => t.Archived == false));
            }
            else
            {
                return View(tickets);
            }
        }

        // GET: Archived Ticket
        public async Task<IActionResult> ArchivedTickets()
        {
            int companyId = User.Identity.GetCompanyId();

            List<Ticket> tickets = await _ticketService.GetArchivedTicketsAsync(companyId);
            
            return View(tickets);
        }

        // GET: Unassigned Tickets
        [Authorize(Roles = "Admin, ProjectManager")]
        public async Task<IActionResult> UnassignedTickets()
        {
            int companyId = User.Identity!.GetCompanyId();
            string btUserId = _userManager.GetUserId(User);

            List<Ticket> tickets = await _ticketService.GetUnassignedTicketsAsync(companyId);

            if (User.IsInRole(nameof(BTRole.Admin)))
            {
                return View(tickets);
            }
            else
            {
                List<Ticket> pmTickets = new();

                foreach (Ticket ticket in tickets)
                {
                    if (await _projectService.IsAssignedProjectManagerAsync(btUserId, ticket.ProjectId))
                    {
                        pmTickets.Add(ticket);
                    }
                }

                return View(pmTickets);
            }
        }

        [Authorize(Roles = "Admin, ProjectManager")]
        [HttpGet]
        public async Task<IActionResult> AssignDeveloper(int id)
        {
            return View();
        }


        [Authorize(Roles = "Admin, ProjectManager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignDeveloper(AssignDeveloperViewModel model)
        {
            if (model.DeveloperId != null)
            {
                BTUser btUser = await _userManager.GetUserAsync(User);

                try
                {
                    await _ticketService.AssignTicketAsync(model.Ticket.Id, model.DeveloperId);
                }
                catch (Exception e)
                {
                    throw;
                }

                //New Ticket
                Ticket newTicket = await _ticketService.GetTicketAsNoTrackingAsync(model.Ticket.Id);
                await _ticketHistoryService.AddHistoryAsync(oldTicket, newTicket, btUser.Id);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTicketComment([Bind("Id, TicketId, Comment")] TicketComment ticketComment)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ticketComment.UserId = _userManager.GetUserId(User);
                    ticketComment.Created = DateTime.UtcNow;

                    await _ticketService.AddTicketCommentAsync(ticketComment);

                    //Add history
                    await _ticketHistoryService.AddHistoryAsync(ticketComment.TicketId, nameof(TicketComment),
                        ticketComment.UserId);
                }
                catch (Exception e)
                {
                    throw;
                }
            }

            return RedirectToAction("Details", new {id = ticketComment.TicketId});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTicketAttachment(
            [Bind("Id, FormFile, Description, TicketId")]
            TicketAttachment ticketAttachment)
        {
            string statusMessage;
            ModelState.Remove("UserId");

            if (ModelState.IsValid && ticketAttachment.ImageFormFile != null)
            {
                try
                {
                    ticketAttachment.ImageFileData =
                        await _fileService.ConvertFileToByteArrayAsync(ticketAttachment.ImageFormFile);
                    ticketAttachment.ImageFileName = ticketAttachment.ImageFormFile.FileName;
                    ticketAttachment.ImageContentType = ticketAttachment.ImageFormFile.ContentType;

                    ticketAttachment.Created = DateTime.UtcNow;
                    ticketAttachment.UserId = _userManager.GetUserId(User);

                    await _ticketService.AddTicketAttachmentAsync(ticketAttachment);

                    //Add history
                    await _ticketHistoryService.AddHistoryAsync(ticketAttachment.TicketId, nameof(ticketAttachment),
                        ticketAttachment.UserId);
                }
                catch (Exception e)
                {
                    throw;
                }

                statusMessage = "Success: New attachment added to Ticket."
            }
        }

        public async Task<IActionResult> ShowFile(int id)
        {
            return View();
        }


        // GET: Tickets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Ticket ticket = await _ticketService.GetTicketByIdAsync(id.Value);

            if (ticket == null)
            {
                return NotFound();
            }

            return View(ticket);
        }

        // GET: Tickets/Create
        public async Task<IActionResult> Create()
        {
            BTUser btUser = await _userManager.GetUserAsync(User);


            if (User.IsInRole(nameof(BTRole.Admin)))
            {
                ViewData["ProjectId"] =
                    new SelectList(await _projectService.GetAllProjectsByCompanyAsync(btUser.CompanyId), "Id", "Name");
            }
            else
            {
                ViewData["ProjectId"] =
                    new SelectList(await _projectService.GetUserProjectsAsync(btUser.Id), "Id", "Name");
            }

            ViewData["TicketPriorityId"] = new SelectList(await _lookupService.GetTicketPrioritiesAsync(), "Id", "Name");
            ViewData["TicketTypeId"] = new SelectList(await _lookupService.GetTicketTypesAsync(), "Id", "Name");

            return View();
        }

        // POST: Tickets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(
            [Bind("Id,Title,Description,ProjectId,TicketTypeId,TicketPriorityId")] Ticket ticket)
        {

AtlasTracker/Views/Tickets/AllTickets.cshtml
@model IEnumerable<AtlasTracker.Models.Ticket>
@using Microsoft.AspNetCore.Identity
@using AtlasTracker.Services.Interfaces
@using AtlasTracker.Models.Enums
@using Microsoft.AspNetCore.Authorization.Infrastructure

@inject UserManager<BTUser> UserManager
@inject IBTProjectService ProjectService

@{
    ViewData["Title"] = "All Tickets";
    BTUser btUser = await UserManager.GetUserAsync(User);
}

<h1>All Tickets</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Updated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Archived)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArchivedByProject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Project)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TicketPriority)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TicketType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TicketStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OwnerUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeveloperUser)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Updated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Archived)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArchivedByProject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Project.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketPriority.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketType.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketStatus.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OwnerUser.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeveloperUser.FullName)
            </td>
            <td>

                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                @if (User.IsInRole(nameof(BTRole.Admin)) || item.DeveloperUserId == btUser.Id || item.OwnerUserId == btUser.Id || await ProjectService.IsAssignedProjectManagerAsync(btUser.Id, item.ProjectId))
                {
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                }

                @if (User.IsInRole(nameof(BTRole.Admin)) || await ProjectService.IsAssignedProjectManagerAsync(btUser.Id, item.ProjectId))
                {
                    if (item.Archived)
                    {
                        <a asp-action="Restore" asp-route-id="@item.Id">Restore</a>
                    }
                    else
                    {
                        <a asp-action="Archive" asp-route-id="@item.Id">Archive</a>
                    }
                }

            </td>
        </tr>
    }
    </tbody>
</table>

AtlasTracker/Views/Tickets/Archive.cshtml
@model Ticket

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

AtlasTracker/Views/Tickets/ArchivedTickets.cshtml
@model IEnumerable<AtlasTracker.Models.Ticket>
@using Microsoft.AspNetCore.Identity
@using AtlasTracker.Services.Interfaces
@using AtlasTracker.Models.Enums
@using Microsoft.AspNetCore.Authorization.Infrastructure

@inject UserManager<BTUser> UserManager
@inject IBTProjectService ProjectService

@{
    ViewData["Title"] = "Archived Tickets";
    BTUser btUser = await UserManager.GetUserAsync(User);
}

<h1>Archived Tickets</h1>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Updated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Archived)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArchivedByProject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Project)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TicketPriority)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TicketType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TicketStatus)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OwnerUser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeveloperUser)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Created)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Updated)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Archived)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArchivedByProject)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Project.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketPriority.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketType.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketStatus.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OwnerUser.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeveloperUser.FullName)
            </td>
            <td>

                <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
                
                @if (User.IsInRole(nameof(BTRole.Admin)) || await ProjectService.IsAssignedProjectManagerAsync(btUser.Id, item.ProjectId))
                {
                    <span>|</span>
                    if (item.Archived)
                    {
                        <a asp-action="Restore" asp-route-id="@item.Id">Restore</a>
                    }
                    else
                    {
                        <a asp-action="Archive" asp-route-id="@item.Id">Archive</a>
                    }
                }

            </td>
        </tr>
    }
    </tbody>
</table>

AtlasTracker/Views/Tickets/AssignDeveloper.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

AtlasTracker/Views/Tickets/Create.cshtml
@model AtlasTracker.Models.Ticket

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProjectId" class="control-label"></label>
                <select asp-for="ProjectId" class ="form-control" asp-items="ViewBag.ProjectId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TicketTypeId" class="control-label"></label>
                <select asp-for="TicketTypeId" class ="form-control" asp-items="ViewBag.TicketTypeId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TicketPriorityId" class="control-label"></label>
                <select asp-for="TicketPriorityId" class ="form-control" asp-items="ViewBag.TicketPriorityId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AtlasTracker/Views/Tickets/Details.cshtml
@model AtlasTracker.Models.Ticket

@using AtlasTracker.Models.Enums
@using AtlasTracker.Services.Interfaces
@using Microsoft.AspNetCore.Identity

@inject UserManager<BTUser> UserManager
@inject IBTProjectService ProjectService
@inject IBTTicketHistoryService HistoryService
@inject IBTFileService FileService

@{
    ViewData["Title"] = "Details";
	BTUser btUser = await UserManager.GetUserAsync(User);
	BTUser projectManager = await ProjectService.GetProjectManagerAsync(Model.ProjectId);
}


<h1>Ticket Details</h1>

<div>
	<div classxfont-weighteighteightgetainer-fluid">
		<div class="row gy-2">
			<div class="col-md-12 col">
				<div class="row col-cols-2 mt-5 bg-secondary">
					<div class="card col m-1 p-2">
						<div class="card-body">
							<h5>@Model.Title</h5>
							<p>@Model.Description</p>
							<div class="progress-container progress-info m-b-25">
								<span class="progress-badge" style="font-size:small">Project: @Model.Project.Name</span>
								<div class="progress">
									@{
										var start = Model.Project.StartDate.DateTime;
										var end = Model.Project.EndDate.DateTime;
										var today = DateTime.UtcNow;
										var percent = today >= end ? 100 : today < start ? 0 : Math.Round((today.Subtract(start)) / (end.Subtract(start)) * 100);
									}
									<div class="progress-bar" role="progressbar" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100">@percent>
										<span class="progress-value">@percent</span>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="card col m-1 p-2">
						<div class="card-body">
							<ul class="list-unstyled">
								<li><strong>Date Entered:</strong> <span class="">@Model.Created.ToString("dd MMM, yyyy")</span></li>
								<li><strong>Deadline:</strong> <span class="">@Model.Project.EndDate.ToString("dd MMM, yyyy")</span></li>
								<li><strong>Type:</strong> <span class="">@Model.TicketType.Name</span></li>
								<li><strong>Priority:</strong> <span class="">@Model.TicketPriority.Name</span></li>
								<li><strong>Status:</strong> <span class="">@Model.TicketStatus.Name</span></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-8 col col-cols-2 mt-5 ">
				<div class="col">
					<div class="bg-secondary">
						<div class="card m-1 p-2">
							<div class="card-header">
								<h2>Comments</h2>
							</div>
							<div class="card-body" style="overflow-y:auto;height:600px;">
								@*Form and Logic for authorized users to add comments*@
								<form class="form-horizontal form-bordered" asp-action="AddTicketComment" asp-controller="Tickets" method="post">
									<input type="hidden" asp-for="Id" name="TicketId" />
								</form>
								
								<hr />
									<h6>Comments</h6>
									<ul class="right_chat list-unstyled mb-0">
										@*Loop to show comments made for the Ticket*@
									</ul>
							</div>
							<div class="card-footer">
							</div>
						</div>
					</div>
				</div>
				<div class="col">
					<div class="bg-secondary">
						<div class="card m-1 p-2">
							<div class="card-header">
								<h2>Attachments</h2>
							</div>
							<div class="card-body" style="overflow-y:auto;height:300px;">
						
					         @* Refer to the Ticket Attachments document for this section *@
						
							@* Ticket attachments part 1 here *@
											
														    
						        @* Ticket attachments part 2 here *@
														    
							</div>
							<div class="card-footer">
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-4 col mt-5 ">
				<div class="bg-dark">
					<div class="card m-1 p-2">
						<div class="card-header">
							<h2>History</h2>
							<hr />
						</div>
						<div class="card-body" style="overflow-y:auto;height:1000px;background-color:antiquewhite">
							@*Loop to show the history entries for the Ticket*@
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
																	  

AtlasTracker/Views/Tickets/Edit.cshtml
@model AtlasTracker.Models.Ticket

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Ticket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="ProjectId" />
            <input type="hidden" asp-for="Created" />
            <input type="hidden" asp-for="OwnerUserId" />
            <input type="hidden" asp-for="DeveloperUserId"/> 
            <input type="hidden" asp-for="Archived"/> 
            
            
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TicketTypeId" class="control-label"></label>
                <select asp-for="TicketTypeId" class="form-control" asp-items="ViewBag.TicketTypeId"></select>
                <span asp-validation-for="TicketTypeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TicketPriorityId" class="control-label"></label>
                <select asp-for="TicketPriorityId" class="form-control" asp-items="ViewBag.TicketPriorityId"></select>
                <span asp-validation-for="TicketPriorityId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TicketStatusId" class="control-label"></label>
                <select asp-for="TicketStatusId" class="form-control" asp-items="ViewBag.TicketStatusId"></select>
                <span asp-validation-for="TicketStatusId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AtlasTracker/Views/Tickets/Restore.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Restore</h2>

AtlasTracker/Views/Tickets/ShowFile.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

AtlasTracker/Views/Tickets/UnassignedTickets.cshtml
@model System.Collections.Generic.List<AtlasTracker.Models.Ticket>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>