AtlasTracker/Models/ViewModels/ManageUserRolesViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AtlasTracker.Models.ViewModels;

public class ManageUserRolesViewModel
{
    public BTUser? BtUser { get; set; }
    public MultiSelectList? Roles { get; set; }
    public List<string>? SelectedRoles { get; set; }
    
    
    
    
}

AtlasTracker/Controllers/UserRolesController.cs
using AtlasTracker.Extensions;
using AtlasTracker.Models;
using AtlasTracker.Models.ViewModels;
using AtlasTracker.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AtlasTracker.Controllers;

[Authorize(Roles = "Admin")]
public class UserRolesController : Controller
{
    private readonly IBTRolesService _rolesService;
    private readonly IBTCompanyInfoService _companyInfoService;

    public UserRolesController(IBTRolesService rolesService, IBTCompanyInfoService companyInfoService)
    {
        _rolesService = rolesService;
        _companyInfoService = companyInfoService;
    }

    public IActionResult Index()
    {
        return View();
    }

    // GET
    [HttpGet]
    public async Task<IActionResult> ManageUserRoles()
    {
        // 1. Add an instance of the ViewModel as a list (model)
        List<ManageUserRolesViewModel> model = new();


        // 2. Get CompanyId
        int companyId = User.Identity!.GetCompanyId();

        // Get all company users
        List<BTUser> users = await _companyInfoService.GetAllMembersAsync(companyId);
        // 3. Loop over the users to populate the ViewModel
        //      - instantiate ViewModel
        //      - use _rolesService
        //      - create multi-selects
        foreach (BTUser user in users)
        {
            ManageUserRolesViewModel viewModel = new();
            viewModel.BtUser = user;
            IEnumerable<string> selected = await _rolesService.GetUserRolesAsync(user);
            viewModel.Roles = new MultiSelectList(await _rolesService.GetRolesAsync(), "Name", "Name", selected);

            model.Add(viewModel);
        }

        // 4. Return model to the View 
        return View(model);
    }


    // POST
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ManageUserRoles(ManageUserRolesViewModel member)
    {
        // Get the company Id
        int companyId = User.Identity.GetCompanyId();

        // Instantiate the BTUser
        BTUser btUser = (await _companyInfoService.GetAllMembersAsync(companyId)).FirstOrDefault(u => u.Id == member.BtUser?.Id);
        
        // Get roles for the user
        IEnumerable<string> roles = await _rolesService.GetUserRolesAsync(btUser!);
        
        // Get Selected Roles for the User
        string userRole = member.SelectedRoles?.FirstOrDefault()!;

        if (!string.IsNullOrEmpty(userRole))
        {
            // Remove user from their roles
            if (await _rolesService.RemoveUserFromRolesAsync(btUser!, roles))
            {
                // Add user to a new role
                await _rolesService.AddUserToRoleAsync(btUser!, userRole);
            }
        }
        // Navigate back to the view
        return RedirectToAction(nameof(ManageUserRoles));
    }
}

AtlasTracker/Views/UserRoles/Index.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

AtlasTracker/Views/UserRoles/ManageUserRoles.cshtml
@model IEnumerable<AtlasTracker.Models.ViewModels.ManageUserRolesViewModel>





<div class="row">
    <h2 class="m-t-0 h3"><b>Manage Member Roles </b></h2>
    @foreach (var member in Model)
    {
        <div class="row">
            <div class="card col-4 m-3">
                <div class="card-body">
                    <p class="text-muted font-13 m-b-30">
                        This form displays the current roles assigned to the user: <strong class="text-info">@member.BtUser.FullName</strong>.
                        Use the dropdown to select the roles this user should be assigned.
                        Once roles are selected, click "Assign Roles" to submit the form.
                    </p>
                    <hr />
                    <form asp-action="ManageUserRoles" asp-controller="UserRoles" method=post>
                        <input type="hidden" asp-for="@member.BtUser.Id" />
                        <div class="row">
                            <div class="col-6">
                                <div class="form-group">
                                    <label asp-for="@member.Roles" class="custom-label"> Roles for @member.BtUser.FullName </label>
                                    <select asp-for="@member.SelectedRoles" class="form-control" asp-items="@member.Roles" multiple>

                                    </select>
                                    <hr />
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Assign Role" class="btn btn-info" /> 
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    }
</div>